apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo2-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/demo2-app
    repoURL: https://your-git-repo-url
    targetRevision: HEAD
    plugin:
      name: ksops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
