apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo2-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/alejandraRamos/argocd-gitops.git
    targetRevision: HEAD
    path: apps/demo2-app/
    plugin:
      name: ksops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
