apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-app
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  strategy: {}
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: alejandraramos/demo:73afefc
        name: demo-app
        envFrom:
        - ConfigMapRef:
            name: demo-app-env
        imagePullPolicy: Always
        ports: 
        - containerPort: 80